import React, {useState, useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight, ArrowRight, Asterisk, InstagramLogo, List, X, Megaphone, VideoCamera, UsersThree, PenNib, Storefront, FilmSlate, Sparkle} from '@phosphor-icons/react';
import './style.css';
import HeroCollage from './HeroCollage.jsx';
import ContactPrompt from './ContactPrompt.jsx';
import ContactSheet, {openContact, INSTAGRAM, WHATSAPP, EMAIL, MAILTO} from './ContactSheet.jsx';
import JoinSheet, {openJoin} from './JoinSheet.jsx';
import Doodle from './Doodles.jsx';
import {WhatsappLogo, EnvelopeSimple} from '@phosphor-icons/react';
import {SpeedInsights} from '@vercel/speed-insights/react';

const instagram=INSTAGRAM;
function App(){const[menu,setMenu]=useState(false);useEffect(()=>{const close=e=>{if(e.key==='Escape')setMenu(false)};window.addEventListener('keydown',close);
// ponytail: one observer for every reveal; stagger by sibling index
const items=[...document.querySelectorAll('.hero-copy>*,.hero-art,.section>:not(.doodle),.service,.steps article,.audience-card,.faq-list details,.contact>:not(.doodle):not(.contact-asterisk)')];
items.forEach((el,i)=>{el.classList.add('reveal');el.style.setProperty('--i',[...el.parentElement.children].indexOf(el))});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:0,rootMargin:'0px 0px 60px 0px'});
items.forEach(el=>io.observe(el));
const onScroll=()=>document.body.classList.toggle('scrolled',scrollY>40);onScroll();addEventListener('scroll',onScroll,{passive:true});
// ponytail: cursor parallax on collage labels, pointer devices only
const art=document.querySelector('.hero-art');const fine=matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion:reduce)').matches;
let raf=0,last=null;
const onMove=e=>{last=e;if(raf)return;raf=requestAnimationFrame(()=>{raf=0;const r=art.getBoundingClientRect();const x=(last.clientX-r.left)/r.width-.5,y=(last.clientY-r.top)/r.height-.5;art.style.setProperty('--px',x.toFixed(3));art.style.setProperty('--py',y.toFixed(3))})};
const onLeave=()=>{art.style.setProperty('--px',0);art.style.setProperty('--py',0)};
if(fine&&art){art.addEventListener('mousemove',onMove);art.addEventListener('mouseleave',onLeave)}
return()=>{window.removeEventListener('keydown',close);io.disconnect();removeEventListener('scroll',onScroll);if(art){art.removeEventListener('mousemove',onMove);art.removeEventListener('mouseleave',onLeave)}}},[]);return <>
<a className="skip" href="#main">Skip to content</a>
<header><a href="#" className="brand"><img src="/pixel-union-logo.webp" alt="" width="609" height="540"/><span>pixel union<span className="brand-dot">.</span><small>YOUR SOCIAL MEDIA SUCCESS, UNITED.</small></span></a><nav className={menu?'open':''} aria-label="Main navigation">{[['What we do','services'],['The union','about'],['FAQ','faq']].map(([label,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}<a href={instagram} target="_blank" rel="noreferrer" onClick={()=>setMenu(false)}>Instagram</a>{null}<button className="nav-join" onClick={()=>{setMenu(false);openJoin()}}>Join us</button><button className="nav-cta" onClick={()=>{setMenu(false);openContact()}}>Let’s talk <ArrowUpRight size={18}/></button></nav><button className="menu-toggle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X size={26}/>:<List size={26}/>}</button></header>
<main id="main"><section className="hero"><Doodle icon="tripod" size={150} rotate={-8} style={{left:'2%',bottom:'4%'}} hideMobile/><Doodle icon="phone" size={88} rotate={14} style={{left:'46%',top:'6%'}} hideMobile/><Doodle icon="aperture" size={120} rotate={20} style={{right:'-2%',top:'2%'}}/><Doodle icon="star" size={34} rotate={12} over tone="yellow" style={{left:'38%',top:'46%'}} hideMobile/><div className="hero-copy"><div className="eyebrow"><span className="small-square"/> ROOTED IN ODISHA. MADE FOR EVERYWHERE.</div><h1><span className="line"><span>GOOD BRANDS.</span></span><span className="line"><span>GREAT STORIES.</span></span><span className="line"><span className="red-word">REAL IMPACT.</span></span></h1><p>We make brands part of the conversation.<br/>Creator-led campaigns, scroll-stopping content,<br className="desktop"/> and collaborations that feel like a perfect match.</p><p className="audience-line" aria-label="Made for shop owners, reel creators, and growing brands">Made for <span className="audience-window" aria-hidden="true"><span className="audience-reel"><span>shop owners.</span><span>reel creators.</span><span>growing brands.</span><span>shop owners.</span></span></span></p><div className="hero-actions"><button className="button dark" onClick={openContact}>Let’s make some noise <ArrowUpRight size={21}/></button><a className="text-link" href="#services">Explore our services <ArrowRight size={19}/></a></div><div className="hero-note"><span>YOUR SOCIAL MEDIA SUCCESS, UNITED.</span><span><span className="scroll-cue">↓</span> SCROLL TO MEET THE UNION</span></div></div><HeroCollage/></section>
<div className="ribbon-wrap"><div className="ribbon" aria-label="Creative services"><div className="ribbon-inner">{[0,1,2].map(k=><span className="ribbon-track" key={k} aria-hidden={k?true:undefined}>{['SOCIAL CONTENT','CREATOR PARTNERSHIPS','BRAND STORIES','CULTURE FIRST','CREATOR-LED CAMPAIGNS','COLLABORATIONS','ROOTED IN ODISHA'].map(t=><React.Fragment key={t}>{t} <Asterisk weight="fill"/></React.Fragment>)}</span>)}</div></div></div>

<section id="for-you" className="section audience"><Doodle icon="camera" size={170} rotate={-12} style={{left:'-1%',top:'8%'}} hideMobile/><Doodle icon="reel" size={130} rotate={18} style={{right:'3%',top:'0'}}/><Doodle icon="shop" size={54} rotate={-10} over tone="red" style={{left:'calc(33.33% - 42px)',top:'42%'}} hideMobile/><Doodle icon="play" size={46} rotate={10} over tone="yellow" style={{right:'2%',bottom:'6%'}}/><Doodle icon="heart" size={38} rotate={-14} over tone="red" style={{left:'62%',top:'38%'}} hideMobile/><div className="section-top"><span className="eyebrow">00 / WHO THIS IS FOR</span><span className="tiny">IF YOU HAVE SOMETHING WORTH SHOWING, WE’RE LISTENING.</span></div><h2>Made for the people<br/><span>who make things happen.</span></h2><div className="audience-grid">{[{icon:Storefront,tag:'SHOP OWNERS',title:'Your store deserves a spotlight.',text:'Turn your counter, your craft, and your regulars into content that brings new faces through the door.',hook:'From local shop to local favourite.'},{icon:FilmSlate,tag:'REEL CREATORS',title:'Your audience is your superpower.',text:'Partner with brands that fit your voice. We match you with campaigns and handle the brief, so you keep creating.',hook:'Create more. Chase less.'},{icon:Sparkle,tag:'BRANDS',title:'Your story, told by real people.',text:'Creator-led campaigns, scroll-stopping reels, and social content that feels like culture, not an ad.',hook:'Made in Odisha. Built to travel.'}].map((a,i)=><article className="audience-card" key={a.tag} style={{'--i':i}}><div className="audience-icon"><a.icon size={34} weight="duotone"/></div><small>{a.tag}</small><h3>{a.title}</h3><p>{a.text}</p><span className="audience-hook">{a.hook}</span><button className="text-link" onClick={openContact}>Let’s talk <ArrowUpRight size={17}/></button></article>)}</div></section>
<section id="services" className="section services"><Doodle icon="video" size={150} rotate={10} style={{right:'-1%',top:'2%'}} hideMobile/><Doodle icon="mic" size={110} rotate={-16} style={{left:'1%',bottom:'6%'}}/><Doodle icon="tripod" size={90} rotate={6} style={{left:'52%',top:'4%'}} hideMobile/><Doodle icon="scissors" size={40} rotate={-30} over tone="ink" style={{left:'calc(25% - 22px)',bottom:'-16px'}} hideMobile/><Doodle icon="bulb" size={44} rotate={12} over tone="yellow" style={{right:'4%',top:'34%'}}/><div className="section-top"><span className="eyebrow">01 / WHAT WE BRING</span><span className="tiny">GOOD IDEAS DESERVE GREAT EXECUTION.</span></div><div className="section-heading"><h2>Big ideas.<br/><span>Even better execution.</span></h2><p>From the first spark to the final post,<br/>we bring the right mix of people,<br/>ideas, and craft to your brand.</p></div><div className="service-grid">{[{icon:Megaphone,name:'Social that connects',text:'Give your brand a voice people want to hear. Content ideas, creative direction, and a presence with personality.',tags:'SOCIAL STRATEGY / CONTENT',items:['Monthly content plans','Captions, hooks and hashtags','Page look and feel']},{icon:UsersThree,name:'Creators with chemistry',text:'Bring your brand and the right creators together. Authentic collaborations built around a shared story.',tags:'CREATOR CAMPAIGNS / COLLABS',items:['Creator shortlists that fit','Briefs, timelines and approvals','Collab and UGC campaigns']},{icon:VideoCamera,name:'Content worth a pause',text:'Reels, video, and visual stories made for the way people actually scroll, watch, and share.',tags:'REELS / VIDEO / PRODUCTION',items:['Reels and short video','On-location shoots','Editing, sound and subtitles']},{icon:PenNib,name:'Design with a point',text:'Bold visuals that feel unmistakably you. From everyday social posts to your next big brand moment.',tags:'SOCIAL CREATIVES / CAMPAIGNS',items:['Post and story templates','Launch and campaign creatives','Covers, thumbnails and highlights']}].map((s,i)=><article className="service" key={s.name}><div className="service-number"><s.icon size={29} weight="duotone"/><span>0{i+1}</span></div><h3>{s.name}</h3><p>{s.text}</p><ul className="service-list">{s.items.map(i=><li key={i}>{i}</li>)}</ul><small>{s.tags}</small></article>)}</div></section>
<section className="section formats"><div className="section-top"><span className="eyebrow">02 / WHAT WE MAKE</span><span className="tiny">PICK A FORMAT. WE’LL MAKE IT FEEL LIKE YOU.</span></div><div className="formats-row"><h2>Formats we<br/><span>love to make.</span></h2><ul className="chips">{["Reels", "Shorts", "UGC videos", "Product shoots", "Store walkthroughs", "Founder stories", "Behind the scenes", "Launch teasers", "Menu and product reels", "Event coverage", "Giveaways", "Collab posts", "Testimonial-style reels", "Tutorials and how-tos", "Day-in-the-life"].map((f,i)=><li key={f} style={{'--i':i}}>{f}</li>)}</ul></div></section>
<section id="about" className="section about"><Doodle icon="headphones" size={140} rotate={-10} style={{right:'2%',top:'6%'}} hideMobile/><Doodle icon="palette" size={100} rotate={16} style={{left:'40%',bottom:'4%'}}/><Doodle icon="pin" size={46} rotate={-18} over tone="red" style={{left:'calc(30% - 10px)',top:'12%'}} hideMobile/><Doodle icon="phone" size={44} rotate={22} over tone="ink" style={{left:'6%',bottom:'10%'}}/><div className="about-stamp"><img src="/pixel-union-logo.webp" alt="Pixel Union logo" width="609" height="540" loading="lazy"/><span>LOCAL ROOTS.<br/>LIMITLESS IDEAS.</span></div><div><span className="eyebrow">03 / THE PEOPLE, THE CULTURE, THE UNION</span><h2>From Odisha.<br/>For <em>everywhere.</em></h2><p>We believe the best stories start with something real. A local insight. A shared experience. A voice that feels familiar.</p><p>Pixel Union brings brands, creators, and culture together to turn those moments into content that connects. Rooted in where we come from. Open to wherever your story takes us.</p><a href={instagram} target="_blank" rel="noreferrer" className="text-link">Meet us on Instagram <ArrowUpRight size={20}/></a></div></section>
<section className="section process"><Doodle icon="slate" size={130} rotate={-8} style={{right:'4%',top:'8%'}} hideMobile/><Doodle icon="speaker" size={96} rotate={14} style={{left:'2%',bottom:'2%'}}/><Doodle icon="camera" size={44} rotate={-12} over tone="ink" style={{left:'calc(66.66% - 24px)',bottom:'4%'}} hideMobile/><div className="section-top"><span className="eyebrow">04 / HOW WE MAKE IT HAPPEN</span></div><h2>A good partnership.<br/><span>A simple process.</span></h2><div className="steps">{[['01','We listen.','Tell us about your brand, your audience, and where you want to go.'],['02','We connect the dots.','We shape the story, the creative direction, and the right way to bring it to life.'],['03','We make it happen.','We create, collaborate, and turn the plan into content ready for the world.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section id="faq" className="section faq"><div className="section-top"><span className="eyebrow">05 / GOOD QUESTIONS</span></div><div className="faq-row"><div><h2>Things people<br/><span>usually ask.</span></h2><p className="faq-lead">Still curious? Send a message. Real people reply.</p><button className="text-link" onClick={openContact}>Ask us anything <ArrowUpRight size={17}/></button></div><div className="faq-list">{[["How does a collaboration start?", "You tell us what you’re trying to do, in a DM or a call. We listen, ask a few questions, and come back with an idea of what would work and how we’d get there."], ["I own a shop. What do I need to prepare?", "Honestly, just your shop and your story. We handle the concept, the shoot plan, the creators, and the edit. You bring the thing you’re proud of."], ["I’m a creator. How do I get campaigns?", "Use Join us to tell us your niche, city, and style. When a brand fits your voice, we bring you the brief, the timeline, and the details so you can focus on making."], ["Do you handle shooting and editing?", "Yes. From planning and on-location shoots to editing, sound, subtitles, and covers. If you already have footage, we can work with that too."], ["Do you only work in Odisha?", "Odisha is home and where most of our creators are, but stories travel. If your brand or audience is elsewhere, let’s talk about it."], ["How do you pick creators for a brand?", "By fit first: audience, style, values, and how naturally the product sits in their content. Then we align on brief and creative freedom before anything is made."]].map(([q,a],i)=><details key={q} style={{'--i':i}}><summary>{q}<span className="faq-plus" aria-hidden="true"/></summary><p>{a}</p></details>)}</div></div></section>
<ContactPrompt/></main>
<ContactSheet/><JoinSheet/><SpeedInsights/>
<footer><a className="footer-brand" href="#">pixel union.</a><span>Your social media success, united.<br/>From Odisha, for everywhere.</span><div className="footer-links"><a href={instagram} target="_blank" rel="noreferrer"><InstagramLogo size={19}/> @pixel_union_ <ArrowUpRight size={16}/></a><a href={MAILTO}><EnvelopeSimple size={19}/> {EMAIL}</a>{WHATSAPP&&<a href={WHATSAPP} target="_blank" rel="noreferrer"><WhatsappLogo size={19}/> WhatsApp <ArrowUpRight size={16}/></a>}<button className="footer-join" onClick={openJoin}>Join us <ArrowUpRight size={16}/></button></div><small>© {new Date().getFullYear()} Pixel Union</small></footer></>}
createRoot(document.getElementById('root')).render(<App/>);




